### ISSUE TITLE
Dot Code School Suggestion: Feedback for Section 3 - Chapter 2

### ISSUE THREAD

**Issue by animehacker** [shawntabrizi/rust-state-machine#14]
Good tutorial. Just a very minor point, self.block_number is an implicit return so doesn't need the ; semicolon at the end (actually keeping it caused an error for me) but your answer checker wanted to have it.

I don't  know if this is actually something worth mentioning and I'm new to Rust, maybe the compiler is stricter than it used to be.

**Comment by shawntabrizi** [comment]
@animehacker I can't find the code you are suggesting should be fixed. Can you clarify specifically the code that is in the tutorial that should be changed?

**Comment by shawntabrizi** [comment]
going to close this, feel free to reopen if you have a chance to respond
