### ISSUE TITLE
Documentation bug

### ISSUE THREAD

**Issue by wirednkod** [shawntabrizi/rust-state-machine#3]
In the documentation page insert function is missing a `to_string()`:

![image](https://github.com/shawntabrizi/rust-state-machine/assets/5408605/72619ebf-0310-4648-96ff-e6eb5f573b75)

**Comment by shawntabrizi** [comment]
the problem is that `&String` is a borrowed value, so the more general solution is to use `.clone()`.

This should be fixed now, thank you for your patience.
